### PR TITLE
Updating readme of the activity

### LINKED ISSUE #6: Improve Readme

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Fixes https://github.com/sugarlabs/fossrit/issues/6

### CODE REVIEW

**Comment by quozl** [comment]
I don't understand.  This is a copy of the file README?  If so, why would we add a copy?

**Comment by Aniket21mathur** [comment]
Yes, it is a copy of the README but with font style and font size taken care off. It is not a major change. Thanks!

**Comment by quozl** [comment]
Oh, I see.  You haven't removed the old file though; why is that?

**Comment by Aniket21mathur** [comment]
The old file is not required. Removed it. Thanks.

**Comment by quozl** [comment]
Thanks.

**Pull request merged**
